### ISSUE TITLE
Какие-то слишком пустые проекты, кто про себя пишит такое))

### ISSUE THREAD

**Issue by olegGerbylev** [gr1shan1a/SpringApp#1]
Программирую где-то лет 5-6, активно начал заниматься 3 года назад. 

Языки: начал с pascal ABC, потом python. Сейчас имею опыт в C, немного в плюсах, Java, с ней работаю активно год, капаю spring. Какие-то базовые вещи знаю на go. Если сильно будет надо, смогу сделать сайт, есть знания по html, css, js, ts. 

Достаточно быстро учусь, если уделяю много внимания на это и не отвлекаюсь на то, что надо сделать, например, на C, но не особо хочется

Был опыт в команде, распределяли обязанности, отчитывались о проделанной работе

**Comment by gr1shan1a** [comment]
Этот проект пока что в процессе
